accounts/urls.py
from django.urls import path
from accounts import views as account_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('register/', account_views.Register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
]

latihan_ujikom/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # # url home kita
    path('', views.home, name='home'),

    # url account
    path('', include('accounts.urls')),

    # url penjualan
    path('', include('penjualan.urls'))
]

penjualan/urls.py
from django.urls import path
from . import views

app_name = 'penjualan'

urlpatterns = [
    path('tabel/', views.get_all_mymodels, name='read'),
    path('create/', views.create_mymodel, name='create'),
    path('update/<str:kdjual>/', views.update_mymodel, name='update'),
    path('delete/<str:kdjual>/', views.delete_mymodel, name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(blank=True, max_length=20)
    last_name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=False, null=False, max_length=100)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

penjualan/models.py
from django.db import models

# Create your models here.
class MyModel(models.Model):
    kdjual = models.CharField(primary_key=True, max_length=4)
    kdbrg = models.CharField(max_length=4)
    nmbrg = models.CharField(max_length=100)
    tgltrans = models.DateTimeField(auto_now_add=False)
    jumbrg = models.IntegerField()
    hargabrg = models.FloatField()
    totalbyr = models.FloatField()
    
    def save(self, *args, **kwargs):
        if not self.kdjual:
            last_kdjual = MyModel.objects.order_by('-kdjual').first()
            if last_kdjual:
                last_kdjual_number = int(last_kdjual.kdjual[1:])
                new_kdjual_number = last_kdjual_number + 1
                self.kdjual = 'J' + str(new_kdjual_number).zfill(3)
            else:
                self.kdjual = 'J001'
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nmbrg

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        label='<b>Username</b>',
        help_text='<b>Username digunakan pada saat login</b>'
    )
    email = forms.EmailField(
        label='<b>Email</b>',
        max_length=100,
        help_text='<b>Gunakan email bisnis anda.</b>'
    )
    password1 = forms.CharField(
        label='<b>Password</b>',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text='<b>Use Secure Password!</b>'
    )
    password2 = forms.CharField(
        label='<b>Konfirmasi Password</b>',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text='<b>Samakan dengan password di atas</b>',
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

penjualan/forms.py
from django import forms
from .models import MyModel

class MyModelForm(forms.ModelForm):
    tgltrans = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = MyModel
        fields = ['kdbrg', 'nmbrg', 'tgltrans', 'jumbrg', 'hargabrg', 'totalbyr']

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import SignUpForm
from accounts.models import Profile


def Register(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Akun baru telah berhasil dibuat, dengan username: {username}!')
            password = form.cleaned_data.get('password1')
            return redirect("/login/")

        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])

            return render(request=request,
                        template_name="accounts/register.html",
                        context={"form": form})

    form = SignUpForm
    return render(request=request,
                template_name="accounts/register.html",
                context={"form": form})

latihan_ujikom/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

penjualan/views.py
from penjualan.models import MyModel
from django.shortcuts import render, redirect
from penjualan.forms import MyModelForm

# Create
from django.shortcuts import redirect

def create_mymodel(request):
    if request.method == 'POST':
        form = MyModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('penjualan:read')
    else:
        form = MyModelForm()
    return render(request, 'penjualan/form.html', {'form': form})

# Read
def get_mymodel_by_kdjual(kdjual):
    mymodel = MyModel.objects.get(kdjual=kdjual)
    return mymodel

def get_all_mymodels(request):
    mymodels = MyModel.objects.all()
    return render(request, 'penjualan/tabel.html', {'mymodels': mymodels})

# Update
def update_mymodel(request,id):
    mymodel = MyModel.objects.get(pk=id)
    
    data = {
        'kdbrg' : mymodel.kdbrg,
        'nmbrg':  mymodel.nmbrg,
        'tgltrans': mymodel.tgltrans,
        'jumbrg': mymodel.jumbrg,
        'hargabrg': mymodel.hargabrg,
        'totalbyr': mymodel.totalbyr, 
    }
    
    penjualan_form = MyModelForm(request.POST or None, initial=data, instance=mymodel)
    
    if request.method == 'POST':
        if penjualan_form.is_valid():
            penjualan_form.save()
            
        return redirect('penjualan:read')
    
    context = {
        "penjualan_form": penjualan_form,
    }
            
    return render(request, 'penjualan/form.html', context)

# Delete
def delete_mymodel(kdjual):
    mymodel = MyModel.objects.get(kdjual=kdjual)
    mymodel.delete()

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="login">
    </form>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p | safe }}

        <input type="submit" value="submit">
    </form>

{% endblock %}

penjualan/templates/penjualan/form.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Simpan</button>
  </form>
  
{% endblock %}

penjualan/templates/penjualan/tabel.html
{% extends 'base.html' %}

{% block content %}
<table>
    <thead>
      <tr>
        <th>Kode Jual</th>
        <th>Kode Barang</th>
        <th>Nama Barang</th>
        <th>Tanggal Transaksi</th>
        <th>Jumlah Barang</th>
        <th>Harga Barang</th>
        <th>Total Bayar</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
      {% for mymodel in mymodels %}
        <tr>
          <td>{{ mymodel.kdjual }}</td>
          <td>{{ mymodel.kdbrg }}</td>
          <td>{{ mymodel.nmbrg }}</td>
          <td>{{ mymodel.tgltrans }}</td>
          <td>{{ mymodel.jumbrg }}</td>
          <td>{{ mymodel.hargabrg }}</td>
          <td>{{ mymodel.totalbyr }}</td>
          <td>
            <td><a class="btn btn-warning" href="{% url 'penjualan:update' MyModel.kdjual %}">Edit</a></td> 
            <td><a class="btn btn-danger" href="{% url 'penjualan:delete' MyModel.kdjual %}" onclick="return confirm('Data Ini Akan Dihapus Secara Permanen,Anda yakin mau menghapus data ini?');">Delete</a></td>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% include 'nav.html' %}
    {% block content %}

    <!-- content goes here -->

    {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <h3>Anda telah berhasil login!</h3>
{% else %}
    <h4>Anda belum login</h4>

{% endif %}

{% endblock %}

templates/nav.html
<div>
    <ul>
        <li><a href="{% url 'home' %}">home</a></li>

        {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">logout</a></li>
           
        {% else %}
            <li><a href="{% url 'register' %}">register</a></li>
            <li><a href="{% url 'login' %}">login</a></li>
        {% endif %}
    </ul>
</div>